name: saas_gestao_financeira
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.9.1
  supabase: ^2.7.0
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  path_provider: ^2.1.3
  pdf: ^3.10.8
  printing: ^5.12.0
  image_picker: ^1.1.2
  flutter_dotenv: ^5.2.1
  google_fonts: ^6.3.0
  google_mobile_ads: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Use ^3.0.0 para flutter_lints compatível com SDK 3.x.x

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logologin.png
    - assets/logocerta.png
    - .env