name: saas_gestao_financeira
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Altere para 3.0.0 <4.0.0 para compatibilidade mais ampla, ou '>=3.8.1 <4.0.0' se quiser ser mais específico

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.9.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Use ^3.0.0 para flutter_lints compatível com SDK 3.x.x

flutter:
  uses-material-design: true

  assets:
    - assets/